###TEST###
#WikiMedia project: Access the cache generated by the "getting_data.py" code. 
# By using the cache, retrieves and saves the images of the json files.

import requests
import urllib.request

# # # url= "https://nrs.harvard.edu/urn-"
# # # #the url above changes to this page https://ids.lib.harvard.edu/ids/view/


#Test

urllib.request.urlretrieve("https://nrs.harvard.edu/urn-3:HBS.Baker.AC:1083631", "test2_filenamedeliverytag.jpg")